# netlify.toml

[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "out"

[build.environment]
  # Define environment variables here if needed
  # NODE_ENV = "production"

[context.production.environment]
  # Environment variables for production
  # API_KEY = "your-production-api-key"

[context.deploy-preview.environment]
  # Environment variables for deploy previews
  # API_KEY = "your-preview-api-key"

[context.branch-deploy.environment]
  # Environment variables for branch deploys
  # API_KEY = "your-branch-api-key"
